#
# Jekyll configuration
#
#destination: ./_site
auto:        true
lsi:         false # better related posts
server_port: 4000
pygments:    true
permalink:   /:year/:month/:title.html

#
# Site configuration
#
url:          http://localhost:4000
title:        martinciu's dev blog
description:  ruby, rails, javascript, development
keywords:     ruby, rails, javascript, development
author:       Marcin Ciunelis
email:        marcin.ciunelis@gmail.com
