#
# Jekyll configuration
#
#destination: ./_site
auto:        true
lsi:         false # better related posts
server_port: 3000
pygments:    true
permalink:   /:year/:month/:title.html

#
# Site configuration
#
url:          http://martinciu.com
title:        martinciu's dev blog
description:  ruby, rails, javascript, nodejs, coffeescript
keywords:     ruby, rails, javascript, nodejs, coffeescript
author:       Marcin Ciunelis
email:        marcin.ciunelis@gmail.com
